version: '3.8'

services:
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak-server
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    command: start-dev
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    restart: unless-stopped

  sample-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-app
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    networks:
      - keycloak-network
    restart: unless-stopped

volumes:
  keycloak_db_data:

networks:
  keycloak-network:
    driver: bridge